modLoader="javafml"
loaderVersion="[47,)"
license="LGPL-3.0-only"

[[mods]]
modId="castleshift"
version="${version}"
displayName="Castle Shift"
description='''
A structure mod that adds castles to the world.
'''
authors="ksoichiro"
displayURL="https://github.com/ksoichiro/CastleShift"

[[dependencies.castleshift]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.castleshift]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"

[[dependencies.castleshift]]
modId="architectury"
mandatory=true
versionRange="[9.2.14,)"
ordering="AFTER"
side="BOTH"
